import "../../styles/global.css";
import { Metadata } from "next";
import { Providers } from "../(providers)/providers";

export const metadata: Metadata = {
  title: "Amit's resume",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Amit Suthar</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <link rel="icon" href="/gopher.png" />
      </head>
      <body>
        <Providers>
          <div className="layout">{children}</div>
        </Providers>
      </body>
    </html>
  );
}
